const express = require('express')
const router = express.Router()
const passport = require('../config/passport')
const path = require('path')

const restController = require('../controllers/restaurant-controller')
const userController = require('../controllers/user-controller')
const commentController = require('../controllers/comment-controller')
const { generalErrorHandler } = require('../middlewares/error-handler')
const { authenticated, authenticatedAdmin } = require('../middlewares/auth')

const admin = require('./modules/admin')
const upload = require('../middlewares/multer')

router.use(express.urlencoded({ extended: true }))
router.use('/upload', express.static(path.join(__dirname, 'upload')))
router.use('/admin', authenticatedAdmin, admin)
router.get('/signup', userController.signUpPage)
router.get('/signin', userController.signInPage)
router.get('/logout', userController.signOut)
router.get('/restaurants/feeds', authenticated, restController.getFeeds)
router.get('/restaurants/:id/dashboard', authenticated, restController.getDashboard)
router.get('/restaurants/:id', authenticated, restController.getRestaurant)
router.get('/restaurants', authenticated, restController.getRestaurants)
router.get('/users/:id', authenticated, userController.getUser)
router.get('/users/:id/edit', authenticated, userController.editUser)
router.post('/signup', userController.signUp)
router.post('/signin', passport.authenticate('local', { failureRedirect: '/signin', failureMessage: true }), userController.signIn)
router.post('/comments', authenticated, commentController.postComment)
router.post('/favorite/:restaurantId', authenticated, userController.addFavorite)
router.post('/like/:restaurantId', authenticated, userController.addLike)
router.put('/users/:id', authenticated, upload.single('image'), userController.putUser)
router.delete('/comments/:id', authenticatedAdmin, commentController.deleteComment)
router.delete('/favorite/:restaurantId', authenticated, userController.removeFavorite)
router.delete('/like/:restaurantId', authenticated, userController.removeLike)
router.use('/', (req, res) => res.redirect('/restaurants'))
router.use('/', generalErrorHandler)

module.exports = router
